#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri May 28 02:34:17 PST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_main_time_synth -key {Post-Synthesis:sim_1:Timing:tb_main} -tclbatch tb_main.tcl -view /media/aj/Main_drive/Main_storage/Alfred/Ubuntu_storage/RISCV-single-cyle/MP1/tb_behav.wcfg -log simulate.log"
xsim tb_main_time_synth -key {Post-Synthesis:sim_1:Timing:tb_main} -tclbatch tb_main.tcl -view /media/aj/Main_drive/Main_storage/Alfred/Ubuntu_storage/RISCV-single-cyle/MP1/tb_behav.wcfg -log simulate.log

